In [155]:
import tensorflow as tf

In [156]:
random_data=[8, 3, -11,0, 8,-14, 2, 1]

In [157]:
tf_dataset=tf.data.Dataset.from_tensor_slices(random_data)

In [158]:
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [159]:
# to see the data in tf.Tensor() we have to run a loop  
for i in tf_dataset:
    print(i)

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(-11, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(-14, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [160]:
# to see the data from tf.Tensor() to numpy array we have to run a loop  
for i in tf_dataset:
    print(i.numpy())

print("to see the same output as above mention data we can also use : ")
for i in tf_dataset.as_numpy_iterator():
    print(i)

8
3
-11
0
8
-14
2
1
to see the same output as above mention data we can also use : 
8
3
-11
0
8
-14
2
1


In [161]:
# if we want to fetch only 4 data out of given data we can use 

for i in tf_dataset.take(3):
    print(i.numpy())

8
3
-11


In [162]:
# lets say I want to filter the negative dataset I can supply data to a filter function using lambda and it will create new dataset 

tf_dataset2=tf_dataset.filter(lambda x: x>0)
tf_dataset2

<_FilterDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [163]:
# to see the data simply run a loop and it will return only positive values
for i in tf_dataset2:
    print(i.numpy())

8
3
8
2
1


In [164]:
# lets say i want to add something to this data with their each elements of tf_dataset2

for i in tf_dataset2.map(lambda x: x+23):
    print(i.numpy())

31
26
31
25
24


In [165]:
# we can also suffle the data 
tf_dataset3=tf_dataset2.shuffle(3)

for i in tf_dataset3:
    print(i.numpy())

8
8
2
1
3


In [166]:
for i in tf_dataset2:
    print(i.numpy())

8
3
8
2
1


In [167]:
# let say, I want to batch the tf_dataset2 into differnt batch which is useful like supplying dataset two diffent GPU for computation 

for i in tf_dataset2.batch(2):      #tf_dataset2.batch(2)   --> here 2 is the number of element in each batch
    print(i.numpy())

[8 3]
[8 2]
[1]


In [168]:
# converting everything in a single line 
for i in tf_dataset:
    print(i.numpy())

8
3
-11
0
8
-14
2
1


In [169]:
# here it simply converted into on line 

tf_dataset4=tf_dataset.filter(lambda x: x>0).map(lambda y: y+23).shuffle(3).batch(2)     
for i in tf_dataset4:
    print(i.numpy())

[31 26]
[24 31]
[25]


In [170]:
# Load tf_dataset of cat and horse images
# /*/* these two "/*" is for two differnt purpose first to go inside a folder and second is for file inside the function
# example and explaination of given /*/*: 
# "/*"      : >>>>> /cat images - Google Search
# "/*/*"    : >>>>> /cat images - Google Search/2_large (1).jpg

df_cat_horse=tf.data.Dataset.list_files('/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/*/*')   
for i in df_cat_horse:
    print(i.numpy())

b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/canva-aesthetic-cute-cat-pun-phone-wallpaper-xdjiI0JS_GU.jpg'
b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/71YKFdJPUTL.jpg'
b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/Cat-andriyko-podilnyk-RCfi7vgJjUY-unsplash_1659328989095_1659328998370_1659328998370.jpg'
b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/kitty-cat-kitten-pet-45201 (1).jpg'
b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/cat-sneaking-look-from-white-screen_60438-3711 (1).jpg'
b'/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/cat images - Google Search/all-about-tabby-cats-552489-hero-a23a9118af8c477b914a0a1570d4f787.jpg'
b'/home/krishnakumar/Documents/reseach

In [171]:
# this function is use to slice the label from the folder if the image is of "cat" or "horse"
def get_label(file_path):
    import os
    # This part of the code splits the file_path using the directory separator "(os.path.sep)"", which is typically a forward slash ("/") on Unix-like systems or a backslash ("") on Windows.
    return tf.strings.split(tf.strings.split(file_path,os.path.sep)[-2])[0]     


In [172]:
get_label("/home/krishnakumar/Documents/reseach/LLM_reserach/Datasets/Images_horse_cat/horse images - Google Search/1.2fb223e92647f3ce1bb19fe4212f4c04.jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'horse'>

In [173]:
# map the function get_label to get the label of the image like horse and cat using map function merging a function ::get_label() with dataset_path ::df_cat_horse
for i in df_cat_horse.map(get_label):
    print(i.numpy())

b'horse'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'horse'
b'cat'
b'horse'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'horse'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'horse'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'cat'
b'horse'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'cat'
b'cat'
b'horse'
b'cat'
b'horse'
b'cat'
b'horse'
b'horse'
b'horse'
b'horse'
b'h

In [185]:
# this function is use to read image in 3D numpy array and get the label using get_label() integrated inside the preprocess_image()
def preprocess_image(file_path):
    label=get_label(file_path)
    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])
    return img,label


In [186]:
for img,label in df_cat_horse.map(preprocess_image).take(3):
    print("label :",label)                     # this is the label of image
    print("IMAGE:",img[0][0])                  # because 3D array of a image contain a lot of data so just to check getting only one pixel which is in BGR or RGB channel

label : tf.Tensor(b'cat', shape=(), dtype=string)
IMAGE: tf.Tensor([105.     126.      69.0625], shape=(3,), dtype=float32)
label : tf.Tensor(b'cat', shape=(), dtype=string)
IMAGE: tf.Tensor([247.3789  247.3789  245.41016], shape=(3,), dtype=float32)
label : tf.Tensor(b'cat', shape=(), dtype=string)
IMAGE: tf.Tensor([248. 248. 250.], shape=(3,), dtype=float32)


In [187]:
for img,label in df_cat_horse.map(preprocess_image).take(3):
    print("label :",label)                     # this is the label of image
    print("IMAGE:",img)                  

label : tf.Tensor(b'horse', shape=(), dtype=string)
IMAGE: tf.Tensor(
[[[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]

 [[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]

 [[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]

 ...

 [[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]

 [[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]

 [[253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]
  ...
  [253. 205.   0.]
  [253. 205.   0.]
  [253. 205.   0.]]], shape=(128, 128, 3), dtype=float32)
label : tf.Tensor(b'horse', shape=(), dtype=string)
IMAGE: tf.Tensor(
[[[ 46.14514    47.14514    49.14514  ]
  [ 48.835938   49.835938   51.835938 ]
  [ 4

In [188]:
# scaling the image in between 0 to 1 deviding all the number by 255 which is uint 8 datatype.
def scale_img(image,label):
    return image/255,label

In [189]:
# using map function integrate preprocess_image() and scale_img() 
for img,label in df_cat_horse.map(preprocess_image).map(scale_img).take(2):
    print("label :",label)
    print("IMAGE:",img)

label : tf.Tensor(b'cat', shape=(), dtype=string)
IMAGE: tf.Tensor(
[[[0.46371424 0.4441064  0.420577  ]
  [0.32958338 0.31101722 0.2992525 ]
  [0.5842639  0.53800166 0.5233571 ]
  ...
  [0.81795317 0.8022669  0.7552081 ]
  [0.773309   0.7576227  0.7105639 ]
  [0.702978   0.68729174 0.6402329 ]]

 [[0.5542861  0.5346783  0.518992  ]
  [0.7125852  0.67961955 0.672573  ]
  [0.6379428  0.61833495 0.6026487 ]
  ...
  [0.2638478  0.2636946  0.2425853 ]
  [0.6532995  0.60711646 0.5702232 ]
  [0.7846354  0.77246934 0.71484995]]

 [[0.25779238 0.23818456 0.22641985]
  [0.6479167  0.60735244 0.59037966]
  [0.70165324 0.6702807  0.658516  ]
  ...
  [0.9332108  0.9449755  0.90183824]
  [0.91887254 0.92662376 0.8971661 ]
  [0.7989837  0.7832974  0.74016017]]

 ...

 [[0.5994332  0.5876685  0.5602175 ]
  [0.5592065  0.5461249  0.51933235]
  [0.722606   0.70299816 0.6873119 ]
  ...
  [0.7198376  0.7198376  0.6846967 ]
  [0.13267487 0.11306703 0.10130233]
  [0.16536458 0.14575674 0.13007046]]

 [[0.7

# NOTE: this is the overall pipelining using tensorflow for huge dataset if your RAM(like 8GB, 16 GB, etc) is limit you can use it to Train MODEL on your pc to get collapsed.